### PR TITLE
Prevented an error with navigator when used in Node.js & supertest

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Cheers. :)

### CODE REVIEW

**Comment by pipwerks** [comment]
Hi Hugo

Thanks for this. Can you provide more information about what this fixes? 

If I read this correctly, you're saying Node will return false on `typeof window === 'undefined'` and `typeof navigator === 'undefined'` (thereby making PDFObject believe this is a browser), while `navigator.userAgent` and `navigator.mimeTypes` will return false in Node but true in a browser, ensuring PDFObject only fires in a browser?

Thanks

**Comment by HugoGiraudel** [comment]
Hey there,

Our problem is more about the fact that our test environment mocks `window` and `navigator`, but apparently in a very poor way. `navigator` is defined in our case, but `navigator.mimeTypes` is not, which causes your script to crash. For consistency, I also patched `navigator.userAgent` in the PR even if we didn’t have an explicit problem with this.

Does it make sense?

**Comment by pipwerks** [comment]
If this affected all Node users, I'd consider it, but I won't update the library (and corresponding CDN, Bower, NPM, etc) if it only addresses an issue specific to SuperTest. It sounds like SuperTest's `navigator` object should be improved to better mimic a browser environment, regardless of PDFObject.

**Comment by HugoGiraudel** [comment]
I understand your concern. The thing is, we found this out when using supertest but it is very likely that it happens in some other setups as well. Moreover, I just checked and supertest is not responsible for mocking the navigator object. My guess is that there is an underlying lib doing that.

Are you sure you don’t want to consider this? It‘s just defensive code and certainly doesn’t add much to the weight of the lib. The difference will be negligible in a minified version, and completely invisible when gzipped.

**Comment by pipwerks** [comment]
No offense, but I won't make edits to the library for edge cases such as this, as small as the edit may be. I have not received any reports of PDFObject failing in Node environments, so I am not confident this patch will help anyone else. 

Based on your description of the issue, I recommend fixing the pseudo `navigator` in SuperTest, as you are likely to encounter the same issue with other client-side JS libraries -- there are plenty that check `navigator.mimeType` and/or `navigator.userAgent`.

Thank you for your submission though.

**Pull request closed without merging**
