### PR TITLE
Pdfjs

### PR DESCRIPTION
**Pull request by lebbe**
Check if pdfjs is installed as an extension in Opera and Chrome. Also assume that pdf.js is available in Firefox from 19 and up, since it is enabled from default since this version.

### CODE REVIEW

**Comment by pipwerks** [comment]
Sorry for the delayed response. Working on a 2.0 update that appears to work fine with Firefox's PDF.js rendering. Hope to release this month.

Unfortunately, as of iOS 9.2, iPads and iPhones still do not support PDF embedding. A multi-page PDF will only render the first page.

**Comment by lebbe** [comment]
This pull request checks pdf.js in chrome and opera (and if firefox version is > 19). It has nothing to do with iOS at all ...

**Comment by lebbe** [comment]
You should really take a look at this commit for you version 2.0:

https://github.com/pipwerks/PDFObject/pull/46/commits/43c2b6c1a64af49658bb15a7f9ff5a2d3e5697ae

Supporting checking pdf.js as plugin in chrome and opera (and soon vivaldi) is a must-have if we are going to start using 2.0.

**Comment by pipwerks** [comment]
Thank you, but my 2.0 edition already supports PDF.js

**Pull request closed without merging**
